# Generated by Django 4.1.7 on 2023-03-15 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='news title')),
                ('content', models.CharField(max_length=10000, verbose_name='news content')),
                ('numclick', models.IntegerField(default=0)),
                ('file1', models.FileField(blank=True, null=True, upload_to='newsfile/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='newsfile/')),
                ('file3', models.FileField(blank=True, null=True, upload_to='newsfile/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('news_delete', 'Can Delete News'), ('news_create', 'Can Create News'), ('news_update', 'Can Update News')),
            },
        ),
    ]
