# Generated by Django 4.1.7 on 2023-03-13 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="job title", max_length=100, verbose_name="title"
                    ),
                ),
                (
                    "finish",
                    models.BooleanField(
                        default=False,
                        help_text="does job finish",
                        verbose_name="finished",
                    ),
                ),
                ("created", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
